When running rails g in this plugin directory, error is reported: undefined method `require_dependency' for main:Object (NoMethodError) Did you mean?  require_relative
To fix this issue, we need to require active_support/dependencies, so:
1. add dependencies for activesupport
2. require it in engine.rb