Fix issues when running rails command (#16)
* When running rails g in this plugin directory, error is reported:
undefined method `require_dependency' for main:Object (NoMethodError)
Did you mean?  require_relative

To fix this issue, we need to require active_support/dependencies, so:
1. add dependencies for activesupport
2. require it in engine.rb

* OpenProject code has dependencies for files besides lib, when running
rails g, error is reported:
No such file to load -- config/constants/api_patch_registry.rb (LoadError)

To fix this issue, PATH to OpenProject should be added to $LOAD_PATH in
bin/rails.